export * from "./userAction";

export const CONSTANTS = {
    ADD_USER : "ADD_USER",
    REMOVE_USER : "REMOVE_USER",
    LOGGED_OUT : "LOGGED_OUT",
    LOGGED_IN : "LOGGED_IN",
    ACTIVE_COURSE:"ACTIVE_COURSE",
    UPDATE_TOPIC:"UPDATE_TOPIC"
}